before_install:
  - gem install bundler
language: ruby
sudo: false
rvm:
  - "2.3"
  - "2.4"
deploy:
  provider: rubygems
  api_key:
    secure: ZyNbSjlMhANpCAyY6fCbcpnMGWlXoo9YkkhADHwUKGu1Ct4pynPdwnql4QM2GFq3YAUgp0IxRiPQx6xmm5ql/yJpH0MSbVpc30pnbXitS8pxof27qd/0glJmT2SjWNnrvxXyQVUB56RzOeGbk1h4PqJOK9xEBnq0YMfKj85ovCU=
  on:
    tags: true
    ruby: "2.4"
